### ISSUE TITLE
Fine-tuning Mistral using RoSA

### ISSUE THREAD

**Issue by hanlv15** [IST-DASLab/RoSA#1]
I want to fine-tune Mistral, but I encountered some problems when using transformers==4.36.2, such as ImportError: cannot import name '_expand_mask' from 'transformers.models.bloom.modeling_bloom'. Is there any way to solve the problem?

**Comment by MNikdan** [comment]
Hi.

I think Mistral requires transformers>=4.34, while our current version of llm-foundry requires 4.31.0.
I was able to work around this by updating transformers and huggingface_hub directly, and it seems to work. Run the following after installing RoSA.
```
pip install -U transformers==4.34
pip install -U huggingface_hub
```
